// Base de Dados Oficial - Brook Motors (Estoque Atualizado)
const VEHICLES = [
  {
    "id": "146",
    "title": "MITSUBISHI L200 TRITON 3.2 D",
    "brand": "Mitsubishi",
    "year": "2010",
    "year_num": 2010,
    "km": "297000 km",
    "color": "Prata",
    "price": "R$ 92.900",
    "price_num": 92900,
    "images": [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Diesel",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/146"
  },
  {
    "id": "141",
    "title": "BMW X5 XDRIVE30D",
    "brand": "BMW",
    "year": "2018",
    "year_num": 2018,
    "km": "135000 km",
    "color": "Preta",
    "price": "R$ 179.900",
    "price_num": 179900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_4727935b.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_329f8144.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_a8e0df9a.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_330d60ea.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_48493921.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_7b5a3a42.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_fe67a791.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_141_651e9acf.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Diesel",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/141"
  },
  {
    "id": "114",
    "title": "VOLKSWAGEN JETTA CL AB",
    "brand": "Volkswagen",
    "year": "2016",
    "year_num": 2016,
    "km": "160000 km",
    "color": "Prata",
    "price": "R$ 77.900",
    "price_num": 77900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_35056e00.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_38ba1e52.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_79c315a7.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_d8b1b468.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_01c81f80.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_5e744fda.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_8dfec533.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_114_a1fef205.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/114"
  },
  {
    "id": "111",
    "title": "BMW 320I M SPORT FLEX",
    "brand": "BMW",
    "year": "2024",
    "year_num": 2024,
    "km": "33000 km",
    "color": "Branca",
    "price": "R$ 286.982",
    "price_num": 286982,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_e59ff1f7.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_3e04aac5.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_8dd052a1.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_89f9ffea.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_d74689ee.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_2dc3178d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_86ec333e.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_111_eb5f9db9.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/111"
  },
  {
    "id": "109",
    "title": "CHEVROLET ONIX 10MT HB",
    "brand": "Chevrolet",
    "year": "2022",
    "year_num": 2022,
    "km": "68000 km",
    "color": "Branca",
    "price": "R$ 62.900",
    "price_num": 62900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_230f564c.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_b4dbb3d6.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_79759fbe.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_9e7f3de3.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_d38bad57.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_6a609534.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_08995a13.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_109_86319813.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Manual",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/109"
  },
  {
    "id": "104",
    "title": "Chevrolet Tracker LT 1.8 Turbo",
    "brand": "Chevrolet",
    "year": "2018",
    "year_num": 2018,
    "km": "82000 km",
    "color": "Branco",
    "price": "R$ 78.900",
    "price_num": 78900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_9716ff79.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_ece57964.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_e00ab8f4.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_a18da3ee.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_9d1ff2b2.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_9a168237.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_9329605d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_104_465ad770.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/104"
  },
  {
    "id": "99",
    "title": "BMW 320I ACTIVE FLEX",
    "brand": "BMW",
    "year": "2017",
    "year_num": 2017,
    "km": "90000 km",
    "color": "BRANCA",
    "price": "R$ 119.900",
    "price_num": 119900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_128d21cc.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_9573c7d9.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_7c3e5c44.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_d6f0e25a.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_f8360019.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_5a817759.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_c3be0fd9.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_99_8048f586.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/99"
  },
  {
    "id": "96",
    "title": "BMW X1 sDrive ActiveFlex 2.0 Turbo",
    "brand": "BMW",
    "year": "2017",
    "year_num": 2017,
    "km": "145000 km",
    "color": "BRANCO",
    "price": "R$ 105.900",
    "price_num": 105900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_b319a79d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_db4fc47d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_5f624d96.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_4888276e.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_4ba025c5.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_8ef7552d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_f177dd32.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_96_2b617062.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/96"
  },
  {
    "id": "92",
    "title": "HYUNDAI HB20 1.6A RSPEC",
    "brand": "Hyundai",
    "year": "2019",
    "year_num": 2019,
    "km": "118000 km",
    "color": "Branca",
    "price": "R$ 69.900",
    "price_num": 69900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_37f8faea.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_2d652dd1.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_7872e69c.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_da4fe5da.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_648d3b5b.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_bbd844e5.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_247a0b40.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_92_e2b67cda.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/92"
  },
  {
    "id": "91",
    "title": "VOLKSWAGEM T-Croos Highline 1.4 250tsi",
    "brand": "Volkswagen",
    "year": "2020",
    "year_num": 2020,
    "km": "119000 km",
    "color": "Preto",
    "price": "R$ 104.900",
    "price_num": 104900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_295ee98a.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_ac990dc0.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_5e4ba493.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_f0572489.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_c2651a13.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_baa9bcb1.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_47f518af.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_91_82a33595.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/91"
  },
  {
    "id": "89",
    "title": "HONDA HR-V EX HS Sensing 1.5 Flex",
    "brand": "Honda",
    "year": "2023",
    "year_num": 2023,
    "km": "62000 km",
    "color": "Prata",
    "price": "R$ 134.900",
    "price_num": 134900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_f0a7b3cc.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_946d5ac8.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_17500b6f.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_e4ffb19e.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_37306eea.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_55bf17fd.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_6ad488dc.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_89_a4eec48c.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/89"
  },
  {
    "id": "86",
    "title": "VOLKSWAGEN AMAROK V6 HIGH AD4",
    "brand": "Volkswagen",
    "year": "2022",
    "year_num": 2022,
    "km": "115000 km",
    "color": "Prata",
    "price": "R$ 169.900",
    "price_num": 169900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_9239ae65.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_9b27b6f5.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_1fc75b1c.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_48b34ca7.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_58730d30.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_0fcf2a0d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_2d86ccf5.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_86_02d93b1c.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Diesel",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/86"
  },
  {
    "id": "80",
    "title": "BMW 320I M SPORT FLEX",
    "brand": "BMW",
    "year": "2023",
    "year_num": 2023,
    "km": "37000 km",
    "color": "Preta",
    "price": "R$ 278.900",
    "price_num": 278900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_d7b39e9f.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_1c148ccf.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_82bae9b4.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_94983688.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_3c28832d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_db1ce322.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_b76e5608.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_80_acbfefc8.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/80"
  },
  {
    "id": "79",
    "title": "VOLKSWAGEN JETTA",
    "brand": "Volkswagen",
    "year": "2019",
    "year_num": 2019,
    "km": "Cinza",
    "color": "",
    "price": "R$ 142.900",
    "price_num": 142900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_cfdda776.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_69c71f80.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_15b04fcd.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_f96be48f.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_a58d257d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_48af07a8.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_f616e546.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_79_8f0210e5.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/79"
  },
  {
    "id": "74",
    "title": "TOYOTA COROLLA GLI18FLEX",
    "brand": "Toyota",
    "year": "2011",
    "year_num": 2011,
    "km": "207000 km",
    "color": "PRATA",
    "price": "R$ 59.900",
    "price_num": 59900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_b7f04ceb.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_8fd3f338.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_c5a7b8b9.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_78316295.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_b3691fae.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_207d18e6.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_912f3a46.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_74_5b881d88.jpg"
    ],
    "category": "sedans_hatches",
    "category_label": "Sedãs & Hatchs",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/74"
  },
  {
    "id": "50",
    "title": "CHEVROLET C10 Manual 6cc - Placa Preta",
    "brand": "Chevrolet",
    "year": "1974",
    "year_num": 1974,
    "km": "111111 km",
    "color": "VERMELHA",
    "price": "R$ 239.900",
    "price_num": 239900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_16ebd7de.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_6734829c.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_fce97cbc.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_78b36000.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_2b5ad009.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_0da9ab53.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_1fb06077.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_50_e5237647.jpg"
    ],
    "category": "classicos",
    "category_label": "Clássicos & Colecionáveis",
    "cambio": "Manual",
    "combustivel": "Gasolina",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/50"
  },
  {
    "id": "47",
    "title": "FORD DEL REY GHIA",
    "brand": "Ford",
    "year": "1988",
    "year_num": 1988,
    "km": "166000 km",
    "color": "AZUL",
    "price": "R$ 39.900",
    "price_num": 39900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_1d5caef3.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_e7cf9f0e.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_c8e5592f.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_9858e469.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_cfc32f92.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_f50059d4.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_4b5dd091.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_47_32305699.jpg"
    ],
    "category": "classicos",
    "category_label": "Clássicos & Colecionáveis",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/47"
  },
  {
    "id": "45",
    "title": "VOLKSWAGEN Fusca 1.300 - Placa Preta",
    "brand": "Volkswagen",
    "year": "1973",
    "year_num": 1973,
    "km": "119000 km",
    "color": "Ocre Marajo",
    "price": "R$ 31.900",
    "price_num": 31900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_3b9f285b.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_47083b49.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_2bbc0296.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_4c3d217d.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_637a12c9.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_b652849f.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_17935cae.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_45_24fa8b57.jpg"
    ],
    "category": "classicos",
    "category_label": "Clássicos & Colecionáveis",
    "cambio": "Manual",
    "combustivel": "Gasolina",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/45"
  },
  {
    "id": "28",
    "title": "Dodge Ram 1500",
    "brand": "Dodge Ram",
    "year": "2022",
    "year_num": 2022,
    "km": "91757 km",
    "color": "Preta",
    "price": "R$ 325.900",
    "price_num": 325900,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_72fa05f8.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_2365a4e0.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_1bca08dc.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_fe097860.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_9824a90e.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_33f87e11.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_31e731b3.jpg",
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_28_eed25cb4.jpg"
    ],
    "category": "suvs_picapes",
    "category_label": "SUVs & Picapes",
    "cambio": "Automático",
    "combustivel": "Flex",
    "is_featured": true,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/28"
  },
  {
    "id": "24",
    "title": "Volkswagen Fusca",
    "brand": "Volkswagen",
    "year": "1967",
    "year_num": 1967,
    "km": "16000 km",
    "color": "VERMELHA",
    "price": "R$ 65.000",
    "price_num": 65000,
    "images": [
      "https://movcar.com.br/static/uploads/carros/thumbs/carro_24_24de3b69.jpg"
    ],
    "category": "classicos",
    "category_label": "Clássicos & Colecionáveis",
    "cambio": "Manual",
    "combustivel": "Gasolina",
    "is_featured": false,
    "movcar_url": "https://movcar.com.br/catalogo/estevam-motors/veiculo/24"
  }
];
